serverFiles:
  alerting_rules.yml:
    groups:
      - name: k8s.rules
        rules:
          - alert: PodNotRunning
            expr: 'kube_pod_status_phase{phase="Running", namespace="default"} < 2'
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Pod is not running"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in phase {{ $labels.phase }}"
          - alert: ServiceDown
            expr: 'kube_endpoint_address_available{namespace="default"} == 0'
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service has no endpoints"
              description: "Service {{ $labels.service }} in namespace {{ $labels.namespace }} has no available endpoints"
